//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDetail
    {
        public int Id { get; set; }
        public bool Gender { get; set; }
        public int Country { get; set; }
        public int State { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Hobbies { get; set; }
    }
}
