//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerEntities : DbContext
    {
        public CustomerEntities()
            : base("name=CustomerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmpCity> EmpCity { get; set; }
        public virtual DbSet<EmpCountry> EmpCountry { get; set; }
        public virtual DbSet<EmpDetail> EmpDetail { get; set; }
        public virtual DbSet<EmpHobby> EmpHobby { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMaster { get; set; }
        public virtual DbSet<EmpState> EmpState { get; set; }
        public virtual DbSet<TransactionTable> TransactionTable { get; set; }
    }
}
